### ISSUE TITLE
Strip latex markup before displaying

### ISSUE THREAD

**Issue by apc** [bdarcus/citar#535] opened 2022-01-19 18:25 UTC
It'd be nice if titles could be stripped of all markup before display, or at least if users had the option to do so (with a boolean perhaps). 

From what I can tell, it should be possible to do this by adding a function to `citar-display-transform-functions`, so I guess the question is what the best way of doing so using the built-in functions is. 

I'm assuming there are other options you are relying on for removing TeX markup. I tried playing around with some of them e.g. `citar-format-reference`, but kept running into a "Key not found" error for some reason. Will investigate.

**Comment by bdarcus** [comment] 2022-01-19 18:40
> From what I can tell, it should be possible to do this by adding a function to `citar-display-transform-functions`, so I guess the question is what the best way of doing so using the built-in functions is.

This line seems to suggest it shouldn't be necessary, or at least that the `citar-clean-string` function is too simple.

**Comment by apc** [comment] 2022-01-19 18:47
So, to clarify, you would've expected the "\emph" on display here not to be there? (Would you expect, in other words, that `citar-clean-string` to remove them from the title?) 

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/350504/150194479-af79eb3d-a50e-4bbb-8eda-c6f8f70f387b.png">

**Comment by bdarcus** [comment] 2022-01-19 18:49
No; all I'm saying is all fields get run through that function, so the issue is not that it's title; the issue is that function is really basic.

**Comment by apc** [comment] 2022-01-19 18:51
Shouldn't I be using? Or shouldn't 'citar' be converting markup to unicode? (If the former, yes I should, but some of the entries in my long and messy bib file are very old, back from when I was a wee lad...)

**Comment by apc** [comment] 2022-01-19 18:52
Oh, and I probably wasn't clear: my question was whether you expected/intended for 'citar-clean-string' to remove the markup.

**Comment by bdarcus** [comment] 2022-01-19 18:56
> Shouldn't I be using?

Yes ;-)

> my question was whether you expected/intended for 'citar-clean-string' to remove the markup.

It seems sensible to me that we should extend it do that, but I'm not sure how much of a rabbit hole that is, or what would be involved.

**Comment by bdarcus** [comment] 2022-01-19 20:56
I also wonder if this is something that should be handled upstream, in parsebib.

**Comment by apc** [comment] 2022-01-20 01:52
Yeah, that’s way above my pay grade… I’d need to understand how citar makes use of parse in much better than I do in order to have a well founded view on that!

**Comment by bdarcus** [comment] 2022-01-20 03:15
Parsebib does the parsing; citar just accesses the results of that parsing.

**Comment by joostkremers** [comment] 2022-01-20 08:50
Yeah, it would make sense to do it in parsebib, given that parsebib already has the option to return the data in a display-friendly format. Ebib actually has this functionality already, so it would probably just be a matter of moving the relevant code from Ebib to parsebib and adjusting as necessary.

I'll try and find some time in the coming days to look at this. (But I'd also accept a PR. 😉 )

**Comment by bdarcus** [comment] 2022-01-20 11:40
Ok, I created a linked issue.

**Comment by bdarcus** [comment] 2022-03-23 18:09
I'm going to close this @apc, given a) I merged #545 here, and b) the linked issue upstream? You can always reopen if necessary.

**Closed by bdarcus** 2022-03-23 18:09 UTC
Labels: enhancement

**Comment by bdarcus** [comment] 2022-06-16 17:28
This should now just work with today's update to parsbib; now v4.0.

https://github.com/joostkremers/parsebib/commit/83a77ea7e51f78093b1a0f1eb51615ec9295829d

I'll probably bump the requirement then, but we'll have to experiment with the details; for example, see [#543](https://github.com/emacs-citar/citar/issues/532).
