### ISSUE TITLE
citar actions in other buffers

### ISSUE THREAD

**Issue by oatmealm** [bdarcus/citar#445] opened 2021-11-28 12:59 UTC
Is there a trivial way to enable citar in other buffer types, like org-brain's visualized buffer? I can see citation refs being correctly formatted/colored but no way of following. Also *-dwim actions (I'm using embark) do not show anything specific to citar.

**Comment by bdarcus** [comment] 2021-11-28 13:32
> Is there a trivial way to enable citar in other buffer types, like org-brain's visualized buffer? I can see citation refs being correctly formatted/colored but no way of following.

I don't know anything about org-brain.

Seems like it should just work, if that mode is derived from org. Is it?

**Comment by oatmealm** [comment] 2021-11-28 18:42
No, it's not derived from org as far as I can tell. Wondering though what's responsible for the coloring of the cite...? I mean, why is org-cite active? Embark seem to think it's an email address...

```
There are text properties here:
  cite-key             "@Memi1953"
  face                 (org-cite-key org-cite org-ref-bad-cite-key-face)
  font-lock-multiline  t
  help-echo            "Memi. La Statue de Sel, 1953."
  htmlize-link         (:uri "cite:@Memi1953")
  keymap               [Show]
  mouse-face           highlight
```

![Screenshot from 2021-11-28 19-36-13](https://user-images.githubusercontent.com/68159077/143781472-edb08b52-336e-4f00-9845-b5d0cc1d59bd.png)

**Comment by bdarcus** [comment] 2021-11-28 18:53
> Wondering though what's responsible for the coloring of the cite...? I mean, why is org-cite active? Embark seem to think it's an email address...

Good question, but IDK.

Maybe a question for the org-brain dev(s)?

**Comment by bdarcus** [comment] 2021-11-28 19:06
PS - before doing so, you should run `org-element-context` at point on the citation-reference to see what it returns.

**Comment by oatmealm** [comment] 2021-11-28 20:57
> org-element-context

seems to identify it correctly... I think.

```
(citation (:style nil :begin 157 :post-blank 0 :end 173 :contents-begin 163 :contents-end 172 :parent (paragraph (:begin 132 :end 174 :contents-begin 132 :contents-end 174 :post-blank 0 :post-affiliated 132 :mode nil :granularity element :parent nil))))
```

**Comment by bdarcus** [comment] 2021-11-28 21:04
> seems to identify it correctly... I think.

Yes.

In that case, the problem is here:

https://github.com/bdarcus/citar/blob/7815b3e8fc221850624fe729de49a62f041616bf/citar.el#L227-L229

E.g. the `at-point` doesn't run outside the itemized derived modes.

Any thoughts on the best way to deal with this @roshanshariff?

**Comment by roshanshariff** [comment] 2021-11-28 22:37
If `org-brain-visualize-mode` should be treated just like `org-mode` by Citar, then maybe the most straightforward approach is to add it to the alist key in `citar-major-mode-functions`?

**Comment by bdarcus** [comment] 2021-11-28 22:43
Or maybe @oatmealm could ask if it makes sense for that mode to derive from org?

**Comment by oatmealm** [comment] 2021-11-29 06:48
I think the answer would be no because in the readme they are suggesting enabling polymode to be able to edit the text while in the visualized buffer (instead of opening the source org). That might also be the solution for citar I assume? I'll try it later on today.

**Comment by bdarcus** [comment] 2021-11-29 11:28
> Perhaps it would be best to modify that variable locally to include that mode and the org at-point function?

By this I mean something like (syntax untested):

```elisp
(add-to-list 'citar-major-mode-funxtions
  (org-brain-visualize) .
     ((citation-at-point . citar-org-citation-at-point))))

**Comment by oatmealm** [comment] 2021-11-29 14:21
Hi, yes, this seem to have worked.

```
  (add-to-list 'citar-major-mode-functions
               '((org-brain-visualize-mode)  (citation-at-point . citar-org-citation-at-point)))
```

**Comment by bdarcus** [comment] 2021-11-29 14:30
> Hi, yes, this seem to have worked.

Good; I'll close this then.

If you have time, could you a) check if you can edit the wiki, and b) if yes, add something on this?

**Closed by bdarcus** 2021-11-29 14:30 UTC
