### ISSUE TITLE
Symbol’s function definition is void: citar-org-keys-at-point

### ISSUE THREAD

**Issue by oatmealm** [bdarcus/citar#401] opened 2021-11-12 13:28 UTC
**Describe the bug**
Error "Symbol’s function definition is void: citar-org-keys-at-point" when trying to invoke  either `embark-act` or `embark-dwim` on various elements in a plain `org` or `org-roam` buffer.

**To Reproduce**
1. Open a plain or org org-roam file with `citar` enabled (embark integration is implied)
2. Try to invoke either `embark-act` or `embark-dwim` on varions elements in the buffer, i.e. `#+ROAM_REFS` a url etc.

**Expected behavior**
Some default action for the thing-at-point.

**Screenshots**

**Emacs version:**
```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
 of 2021-09-29
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-2e9999783 @ /home/xxx/.emacs.d/.local/straight/build-28.0.50/org/)
- Org-roam: db573bb
```

**Additional context**

**Comment by bdarcus** [comment] 2021-11-12 13:43
I don't have any problems with Embark in org, etc, so obviously can't reproduce this.

Do note that you won't be able to use `embark-act` within the property-drawer, as those aren't actually org citations (which aren't allow in the property drawer).

But even so, you shouldn't get an error.

**Comment by tshu-w** [comment] 2021-11-12 14:07
> Do note that you won't be able to use `embark-act` within the property-drawer, as those aren't actually org citations (which aren't allowed in the property drawer).

I'm facing the same error anywhere in the org file after recent update.

```emacs-lisp
(use-package citar
  :straight t
  :defer t
  :init
  (setq org-cite-insert-processor 'citar
        org-cite-follow-processor 'citar
        org-cite-activate-processor 'citar)
  :config
  (setq citar-at-point-function 'embark-act
        citar-bibliography (mapcar (lambda (file) (concat bibtex-file-path file)) bibtex-files)
        citar-library-paths `(,(concat bibtex-file-path "files/"))
        citar-notes-paths `(,bibtex-notes-path)))
```

**Comment by bdarcus** [comment] 2021-11-12 14:12
@roshanshariff - any idea why these two users would be seeing this behavior now?

Do we need to autoload `citar-org-keys-at-point` (though not clear why we didn't see this earlier)?

**Comment by bdarcus** [comment] 2021-11-12 14:53
> Do we need to autoload `citar-org-keys-at-point` (though not clear why we didn't see this earlier)?

I just committed a change that does this.

Can you two confirm it works, or not, and report back?

**Closed** 2021-11-12 14:52 UTC
Labels: bug

**Comment by oatmealm** [comment] 2021-11-12 16:30
Seems to work now, no error. But I still needed to  require `citar-org` manually. Should I remove the `no-require` clause?

```
(use-package! citar-org
  :no-require
  :bind ; optional
  (:map org-mode-map
        ("C-c b" . #'org-cite-insert)) ; Also bound to C-c C-x C-@
  :custom
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (org-support-shift-select t)
  (when (featurep! :lang org +roam2)
    ;; Include property drawer metadata for 'org-roam' v2.
    (citar-file-note-org-include '(org-id org-roam-ref))))
```

**Comment by roshanshariff** [comment] 2021-11-12 16:43
You don't need to remove the `:no-require`, but you do need to rebuild the autoloads file. If you're using Doom then make sure you've got `(unpin! citar)` somewhere in your configuration (to get the latest version) and run the `doom sync` command.

If you're not using Doom but are using `straight.el` as the package manager, then you should run `M-x straight-rebuild-package RET citar` to do the same thing.

@bdarcus, I'll go through all the functions showing up in `citar-major-mode-functions` and make sure they're autoloaded to avoid this in the future.

**Comment by oatmealm** [comment] 2021-11-12 23:00
Thanks. That's what I did.
