### ISSUE TITLE
problem with embark-act

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/citar#583] opened 2022-05-04 12:42 UTC
I don't exactly know what's going on, but I get very different results if I do these from the minibuffer:

1. `citar-insert-citation` (works fine)
2.  `embark-act` > `citar-insert-citation` (this one inserts the candidate string, which is wrong)

Does anyone else see this?

EDIT: confirmed with emacs -q.

**Comment by oantolin** [comment] 2022-05-04 16:57
If you want `citar-insert-citation` to ignore the candidate string, use

```elisp
(push 'embark--ignore-target (alist-get 'citar-insert-citation embark-target-injection-hooks))
```

(But I'm not sure I fully understand the context so I don't know if simply ignoring the target isthe right thing to do.)

**Comment by bdarcus** [comment] 2022-05-04 18:28
Thanks @oantolin - did something in embark change on this front? I don't recall seeing this earlier.

**Comment by oantolin** [comment] 2022-05-04 20:13
No, nothing changed recently that would affect this, I think.

**Comment by localauthor** [comment] 2022-05-04 20:24
I actually recall coming across this quite a while ago, while working on something else, and I completely forgot to circle back to it. Sorry about that.

The issue also occurs in `citar-insert-keys` and `citar-insert-reference`.

This probably isn't the right way to fix the issue---maybe its a mis-use of `embark-pre-action-hooks`, and there's a preferable method?---but it seem to work :)

```
(add-to-list 'embark-pre-action-hooks '(citar-insert-citation citar--run-action))
(add-to-list 'embark-pre-action-hooks '(citar-insert-keys citar--run-action))
(add-to-list 'embark-pre-action-hooks '(citar-insert-reference citar--run-action))

(defun citar--citar-reference-to-key (type target)
  (let* ((string (substring-no-properties target))
         (list (split-string-and-unquote string " "))
         (key (car (last list))))
    (cons type key)))

(defun citar--run-action (&rest _arg)
  (condition-case nil
      (let* ((action (plist-get _arg :action)))
        (when-let ((target (plist-get _arg :target))
                   (key (cdr (citar--citar-reference-to-key nil target))))
          (funcall action (list key)))
        (when-let (cand (plist-get _arg :candidates))
          (funcall action cand))
        (keyboard-quit))))
```

**Comment by localauthor** [comment] 2022-05-04 20:38
> Do you think this is related to #584 also?

Not sure, I haven't been able to reproduce the issue

**Comment by bdarcus** [comment] 2022-05-04 20:49
Ok.

Could you add some comments to that code? I don't fully understand it.

**Comment by localauthor** [comment] 2022-05-04 21:17
Sure, I'll do it here.

The first function `citar--citar-reference-to-key` transforms the long candidate displayed in the minibuffer (ie, the embark-target known as `citar-reference`) into a key. That is, it turn something like this:

`"Fried, Michael                     2005     Barthes's \emphPunctum                                     Fried2005          article          has:files  has:link  Fried2005"`

into this: `"Fried2005"`

Regarding `citar--run-action`, it is a way of running the desired action (eg, `citar-insert-citation`) on the desired target (key, not reference). 

All functions called by embark hooks are passed three keyword arguments, `:action` (eg `citar-insert-citation`), `:target` (the long citar-reference string above), and `:type` (the embark-target type, eg, "citar-reference").

What `citar--run-action` does is intercept the undesired :target before the :action can be performed (hence the use of '_pre_-action' hook). It then transforms the :target into a key and calls the :action on the key. The `keyboard-quit` at the end of the function stops the process in the "pre-action" stage, essentially making the pre-action the action itself. Kind of fun. :)

This all happens in the `let` and the first `when-let`.

The second 'when-let` is to deal with cases of `embark-act-all`, in which case the `_arg` contains a keyword argument :candidates, which for some reason is a list of keys. 🤷‍♂️ So that list gets passed to the action, and voila.

Let me know if anything could be better clarified.

**Comment by bdarcus** [comment] 2022-05-04 22:02
> The first function `citar--citar-reference-to-key` transforms the long candidate displayed in the minibuffer (ie, the embark-target known as `citar-reference`) into a key.

And why is this necessary, and only an issue in this command, and `citar-insert-keys` and `citar-insert-reference`?

I'm just not totally understanding the actual issue, I guess.

**Comment by bdarcus** [comment] 2022-05-04 22:56
@oantolin - is @localauthor's solution here a reasonable approach?

https://github.com/bdarcus/citar/issues/583#issuecomment-1117868826

**Comment by oantolin** [comment] 2022-05-05 00:38
Well, the proposed solution really abuses the pre-action hook in a clever way... 😄

I'm also not sure I understand the problem, so I don't have an informed opinion yet. The thing is i haven't really been using citar, so I'm not sure about the details of which citar commands take which formats (single key, list of keys, etc.). I'll look into it when I get the chanve.

**Comment by oantolin** [comment] 2022-05-05 00:44
But a solution with no hooks should be possible, I think. I mean citar is proving both the target finder and the actions, so citar just has to agree with itself on single format for the targets.

**Comment by oantolin** [comment] 2022-05-05 06:19
Sorry, it was a bug in Embark! embark-act-all was calling multitarget actions on transformed targets (in this case the keys), while embark-act and embark-dwim were calling them on original candidates (in this case the formatted completion candidates). The correct behavior was for all three to use transformed candidates in the multitarget action case, because the use of original candidates is only meant for actions called interactively, which multitarget actions are not.

Please test, but I think oantolin/embark@d07cb30c0a08c5845a96cfdff82e5f42ce2eaef0 should fix this.

**Comment by localauthor** [comment] 2022-05-05 07:53
Fixed on my end! 🙌

One remaining embark-related question I have is about the placement of the embark-transformer function as a let-binding in `citar-select-ref`: https://github.com/bdarcus/citar/blob/b391e6de49e00cffa8f60a089a01d663b627a678/citar.el#L390

Which calls the function `citar--embark-transformer-alist`: https://github.com/bdarcus/citar/blob/b391e6de49e00cffa8f60a089a01d663b627a678/citar.el#L883-L894

This was added in: 31348e39262e55f531dfe99f690752cbb11ed3b4

Maybe @roshanshariff can explain the reason for using a temporary let-binding (which seems fairly oblique) instead of (the arguably more straightforward) adding a transformer function to `embark-transformers-alist`?

And maybe @oantolin can weigh in on embark best-practices here? I'm obviously prone to abusing  his functions, so figured I'd just ask directly 😉

**Comment by bdarcus** [comment] 2022-05-05 09:20
> Sorry, it was a bug in Embark! embark-act-all was calling multitarget actions on transformed targets (in this case the keys), while embark-act and embark-dwim were calling them on original candidates (in this case the formatted completion candidates).

This sounds like it may also explain problems I was having initially when testing the new marking functionality. I hadn't found time to come back that to figure out what was going on.

In any case, I'll test this in a bit.

**Comment by oantolin** [comment] 2022-05-05 22:52
> I do seem to still have a problem with `embark-at-all`, as when running this, I get a "key not found" error; need to dig into this some more.

Let me know if you figure out how to reproduce the problem, because I did test last night with `embark-act-all` and it worked just fine (so I then investigated what it was doing right that `embark-act` and `embark-dwim` were doing wrong).

> One thing with marking, though: it seems the key bindings aren't working for me. Is that a possible conflict with evil or something?

That definitely sounds like the usual problem with evil.

> If that's the case, is there any workaround?

I'm definitely not an expert on evil but you can:(1) use the Emacs state in Embark Collect buffers, or (2) define your own evil key bindings in the normal state. The commands you'd want to bind in Embark Collect buffers are probably: `embark-act` and `embark-act-all`, which I'm guessing you probably have bound globally already, and then specifically for collect buffers, these:
`embark-collect-mark`,  `embark-collect-unmark`, `embark-collect-unmark-all`, `embark-collect-toggle-marks`.

It may be easier to simply configure embark collect buffer to start in Emacs state (I don't know *how* you set the initial evil state, but I know it's easy to do). And then maybe add bindings for `j` and `k` to `forward-button` and `backward-button`.

**Comment by oantolin** [comment] 2022-05-05 22:58
> Maybe @roshanshariff can explain the reason for using a temporary let-binding (which seems fairly oblique) instead of (the arguably more straightforward) adding a transformer function to `embark-transformer-alist`?

@localauthor I also don't get why the transformer is computed dynamically and then `embark-transformer-alist` is let-bound. I would have expected as you suggest just adding a transformer function to `embark-transformer-alist`. Specifically I think a function like the `lambda` in the body of `citar--embark-transformer-alist` with `candidates` replaced by `(citar--get-candidates)`.

What would be wrong with that? Not speed, because `citar--get-candidates` caches. Maybe there are citar contexts I'm not aware of? That simple function I was proposing assumes every time citar prompts you for a reference it is using the list of references produced by `citar--get-candidates`, maybe that's not true?

**Comment by bdarcus** [comment] 2022-05-05 23:03
> That simple function I was proposing assumes every time citar prompts you for a reference it is using the list of references produced by `citar--get-candidates`, maybe that's not true?

No, it is true.

**Comment by roshanshariff** [comment] 2022-05-05 23:08
Sorry for the late response. If I remember correctly, the original reason for doing that is that the return value of `citar--get-candidates` is buffer-local. It can depend on local bibliographies that are active only for a particular buffer.

But Embark transformers can be called outside of the buffer, for example in the minibuffer during a completing-read. So if the transformer were just a static function that's globally added to `embark-transformer-alist`, it wouldn't have a way to access the relevant buffer-local Citar candidates.

With the current approach, we generate an appropriate transformer for the current buffer, dynamically bind it to the top of the transformer stack, and remove it again when the completing-read is done.

**Comment by bdarcus** [comment] 2022-05-05 23:13
Ah yes; I always forget about local bib files, since I never use them.

**Comment by oantolin** [comment] 2022-05-06 03:24
@roshanshariff, you could use a single static function that uses this expression to figure out which buffer's local bibliography to use:

```elisp
(if (minibufferp)
    (window-buffer (minibuffer-selected-window))
  (current-buffer))
```
I'm not sure that's really better, the current approach definitely works too.

**Comment by localauthor** [comment] 2022-05-06 04:43
Ah, local bibs! Thanks for the explanation  @roshanshariff. 👍

**Comment by bdarcus** [comment] 2022-05-06 12:33
@oantolin 

> Let me know if you figure out how to reproduce the problem, because I did test last night with `embark-act-all` and it worked just fine (so I then investigated what it was doing right that `embark-act` and `embark-dwim` were doing wrong).

This is what I see just before running it.

![image](https://user-images.githubusercontent.com/1134/167131871-582a818a-1780-4dd1-ad0c-8d8cfa00bbbe.png)

When I choose y, nothing happens; no error, but also no content copied.

That "nil" is perhaps off?

**Comment by oantolin** [comment] 2022-05-07 17:02
It feels weird that citar doesn't inherit from `embark-general-map`. I'm very used to being able to delete, duplicate or copy targets to the kill-ring, or to switch to isearch for other occurrences of the same target, etc.😄 I think I'm going to fix that in my personal configuration.

**Comment by oantolin** [comment] 2022-05-07 17:05
Ah, OK, I see a problem with `embark-act-all` now. For me, it works fine from the minibuffer, but if you first use `embark-collect` and then try to use `embark-act-all` from there it inserts formatted candidates rather than keys. That is wrong of course, but it is also different from the behavior you saw, @bdarcus.

**Comment by oantolin** [comment] 2022-05-07 17:07
I think it's this design of let-binding the transformer alist that causes the behavior I see. By the time I try acting on the candidates in the collect buffer, the transfomer is simply gone! I'll changing the transformer to the one I suggested.

**Comment by oantolin** [comment] 2022-05-07 17:16
OK, so the problem I observed (which may or may not be the same one @bdarcus saw) is solved by using the transformer I suggested:

```elisp
(defun citar--reference-transformer (type target)
  "Look up key for a citar-reference."
  (cons type (or (cadr (assoc target
                              (with-current-buffer (embark--target-buffer)
                                (citar--get-candidates)))))))

(add-to-list 'embark-transformer-alist
             '(citar-reference . citar--reference-transformer))
```

I believe simply running `citar--get-candidates` in a certain buffer picks up the local bibliography of that buffer, is that correct?

**Comment by oantolin** [comment] 2022-05-07 17:22
I guess I should ping @roshanshariff too. Would the transformer in the above comment work in place of the dynamically generated transformer currently used? The problem I found with the current solution is that in Embark Collect buffers full of references there is no transformer so I get formatted candidates inserted instead.

**Comment by bdarcus** [comment] 2022-05-07 17:23
Thanks @oantolin.

So just to confirm: there's some small bug in embark still, and a bug in citar too?

> I believe simply running citar--get-candidates in a certain buffer picks up the local bibliography of that buffer, is that correct?

I believe so.

> It feels weird that citar doesn't inherit from embark-general-map.

I'll look at that again. I thought it did now in the minibuffer, if not in the buffer.

**Comment by bdarcus** [comment] 2022-05-07 17:31
> Ah, OK, I see a problem with `embark-act-all` now. For me, it works fine from the minibuffer, but if you first use `embark-collect` and then try to use `embark-act-all` from there it inserts formatted candidates rather than keys. That is wrong of course, but it is also different from the behavior you saw, @bdarcus.

I thought that _was_ what I was seeing?

**Comment by oantolin** [comment] 2022-05-07 17:35
Maybe, I'm not certain it's the same issue and I'm not certain it's a different issue, @bdarcus. 😆 

Try evaluating the code I pasted above and seeing if that fixes your problem.

**Comment by bdarcus** [comment] 2022-05-07 17:43
> Try evaluating the code I pasted above and seeing if that fixes your problem.

It does indeed appear to fix it.

**Comment by bdarcus** [comment] 2022-05-07 17:52
So assuming this does work, does that mean adding this code, and removing that let-binding?

**Comment by oantolin** [comment] 2022-05-07 17:57
> So assuming this does work, does that mean adding this code, and removing that let-binding?

Yes.

**Comment by bdarcus** [comment] 2022-05-07 18:09
OK, I created a quick PR that I've linked here. Still needs testing with local bibs.

**Comment by oantolin** [comment] 2022-05-07 18:26
I left some comments on the PR.

**Comment by bdarcus** [comment] 2022-05-07 18:37
> I left some comments on the PR.

Weird; I can't see any.

**Comment by oantolin** [comment] 2022-05-07 19:08
I see them at this URL: https://github.com/bdarcus/citar/pull/587

**Comment by bdarcus** [comment] 2022-05-07 19:12
Hmm ...maybe something wrong with github?

![image](https://user-images.githubusercontent.com/1134/167268584-04850e15-8e57-43c8-a1a7-64a8aa895214.png)

**Comment by oantolin** [comment] 2022-05-07 19:49
Oh, weird, I'll just copy them here, then.

1. There *is* a variable called `embark--target-buffer`, but the code actually uses a *function* of the same name, not the variable. So you should use `(declare-function 'embark--target-buffer "ext:embark")` instead.
2. Since that was the only use of `citar--embark-transformer-alist` you should also delete that function.

**Comment by bdarcus** [comment] 2022-05-07 19:55
By 2 do you mean use a lambda instead?

**Comment by oantolin** [comment] 2022-05-07 19:58
No, `citar--embark-transformer-alist` is the old function, the one that returns the modified transformer to let-bind. That function is not used at all after your PR, but still present in the source code.

**Comment by bdarcus** [comment] 2022-05-07 21:17
OIC.

OK, I think I've fixed those two issues.

**Closed** 2022-05-08 11:25 UTC
Labels: bug
